/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IElTools: typeof import('~icons/el/tools')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpMoonLi: typeof import('~icons/ep/moon-li')['default']
    IEpMoonLight: typeof import('~icons/ep/moon-light')['default']
    IEpMoonLihj: typeof import('~icons/ep/moon-lihj')['default']
    IEpMoonLiht: typeof import('~icons/ep/moon-liht')['default']
    IEpMoonNight: typeof import('~icons/ep/moon-night')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpSunrise: typeof import('~icons/ep/sunrise')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IETools: typeof import('~icons/e/tools')['default']
    JoBtn: typeof import('./components/Button/JoBtn.vue')['default']
    JoLoadImg: typeof import('./components/Image/JoLoadImg.vue')['default']
    JoMask: typeof import('./components/Mask/JoMask.vue')['default']
    JoModal: typeof import('./components/Modal/JoModal.vue')['default']
    JoPopup: typeof import('./components/Popup/JoPopup.vue')['default']
    JoSwitch: typeof import('./components/Button/JoSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
